# Start

In [ ]:
import warnings; warnings.simplefilter('ignore')

import random

import pandas as pd
import numpy as np
import os
import re

import matplotlib.pyplot as plt
import seaborn as sns
import cufflinks as cf
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

project_dir = r'/content/drive/My Drive/Colab Notebooks/'

%matplotlib inline


# 1.2 Векторы


In [ ]:
# Задание 1.2.1

apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])
apartment

array([5.950e+01, 3.140e+01, 1.900e+01, 2.000e+00, 6.055e+04, 2.000e+00])

In [ ]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]

In [ ]:
apartment = np.delete(apartment, [0, 1])

In [ ]:
apartment = np.append(apartment, share_living_space)

In [ ]:
len(apartment)

5

In [ ]:
round(apartment[-1], 2)

0.53

In [ ]:
# Задание 1.2.2
len(apartment)


5

In [ ]:
# Задание 1.2.3

t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

t[5], t[1]

(28, 14)

In [ ]:
t.min() - t[0], t.max() - t[6]

(0, 0)

## 1.3 Базовые операции над векторами

In [ ]:
# Задание 1.3.3

alex = np.array([120,150,90])
alex_w = np.array([130,130,130])
alex_g = np.array([2, 3, 2.5])*72

In [ ]:
alex_g

array([144., 216., 180.])

In [ ]:
alex + alex_w + alex_g

array([394., 496., 400.])

## 1.4. Линейная комбинация

In [ ]:
# Задание 1.4.1
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])
k = np.array([2,-3,5])

x * k[0] + y * k[1] + u * k[2]

array([7, 7])

In [ ]:
# Задание 1.4.2

make_count = np.array([3, 4, 5, 9])
sell_count = np.array([1, 5, 3, 6])
make_price = 200
sell_price = 400

sell_count * sell_price - make_count * make_price

array([-200, 1200,  200,  600])

In [ ]:
# Задание 1.4.3
x = np.array([-1, -2])
y = np.array([1, 2])

x + y

array([0, 0])

In [ ]:
x = np.array([-3,-2])
y = np.array([1,1])
u = np.array([4,3])
x + y * (-1) + u

array([0, 0])

In [ ]:
x = np.array([-3,-2])
y = np.array([1,1])

x + 2 * y

array([-1,  0])

## 1.5. Скалярное произведение

In [ ]:
# Задание 1.5.2

x = np.array([4,5,-1])
y = np.array([2,0,1])
np.dot(x, y)

7

In [ ]:
# Задание 1.5.4

x = np.array([4,6,1])

round(np.sqrt(np.dot(x,x)), 2)

7.28

In [ ]:
# Задание 1.5.5
# вектора называются ортогональными, если их скалярное произведение равно нулю
# пара №1

x = np.array([4,2,-1])
y = np.array([2,0,1])

np.dot(x, y)

7

In [ ]:
# пара №2

x = np.array([4,5,-1])
y = np.array([0,0,0])

np.dot(x, y)

0

In [ ]:
# пара №3
x = np.array([4,-1])
y = np.array([-1,4])

np.dot(x, y)

-8

In [ ]:
# пара №4

x = np.array([4,-1])
y = np.array([1,4])

np.dot(x, y)

0

## 1.7 Практика

In [ ]:
hut_paradise_df = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
hut_paradise_df

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [ ]:
hut_paradise = hut_paradise_df.values
hut_paradise

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [ ]:
# Задание 1.7.1

hut_paradise[4]

array([40, 33,  1,  6, 20, 16])

In [ ]:
# Задание 1.7.2
# Найдите вектор этажей всех квартир:

hut_paradise[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [ ]:
# Задание 1.7.3
# На каком этаже расположена квартира номер 3?

hut_paradise[2,3]

10

In [ ]:
# Задание 1.7.4
# 0.0/1.0 point (graded)
# Найдите количество квартир:

len(hut_paradise[:,0])

9

In [ ]:
# Задание 1.7.5
# Вычислите вектор нежилой площади:

hut_paradise[:,1] - hut_paradise[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [ ]:
# Задание 1.7.6
# Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны:

hut_paradise[:,0] / 10 *4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [ ]:
# Задание 1.7.7
# Пусть в первой квартире один просмотр занимает 
# 10 минут, 
# во второй — 20 минут,
# в третьей — полчаса, 
# в четверой — 15 минут, 
# в пятой — 5 минут, 
# в шестой — 40 минут, 
# в седьмой — 20 минут, 
# в восьмой — 8 минут и 
# в девятой — 20 минут. 
# Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели:

time_view = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

sum(hut_paradise[:,4] * time_view)


1348

In [ ]:
# Задание 1.7.8
# Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3:

u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

print('(u, v):', u @ v)
print('(u, w):', u @ w)
print('(w, v):', w @ v)

d = v * 2 + w * (-3)
print(d)

print('(w, v):', d @ u)

(u, v): 0
(u, w): 0
(w, v): 0
[-3 14  3  4  2]
(w, v): 0


In [ ]:
# Задание 1.7.10
# Нормируйте векторы . В ответ запишите, округлив до трёх знаков после точки:

# нормировка
u_norm = u /np.linalg.norm(u)
print('u нормированный:', u_norm)
print('третья координата', round(u_norm[2], 3))

u нормированный: [0.8660254  0.         0.28867513 0.28867513 0.28867513]
третья координата 0.289


In [ ]:
# нормировка
v_norm = v /np.linalg.norm(v)
print('v нормированный:', v_norm)
print('четвертая координата', round(v_norm[3], 3))

v нормированный: [ 0.          0.33333333  0.          0.66666667 -0.66666667]
четвертая координата 0.667


In [ ]:
# нормировка
w_norm = w /np.linalg.norm(w)
print('u нормированный:', w_norm)
print('третья координата', round(w_norm[0], 3))

u нормированный: [ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]
третья координата 0.213


# 1.8 Матрицы

## 1.9. Базовые действия над матрицами

In [ ]:
# Задание 1.9.1

a_matrix = np.matrix("1,1;5,7")
b_matrix = np.matrix("6,1;-5,5")

a_matrix + b_matrix

matrix([[ 7,  2],
        [ 0, 12]])

In [ ]:
# Задание 1.9.3

np.matrix("1,5,4;0,1,0").T

matrix([[1, 0],
        [5, 1],
        [4, 0]])

In [ ]:
# Задание 1.9.4
# Выберите верные утверждения:

# 1+
# 2-
# 3-
# 4+
# 5+

## 1.10 Практика

In [ ]:

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])


In [ ]:
# Задание 1.10.1
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
Inc = Inc.T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [ ]:
# Задание 1.10.2

Cons = np.array([ Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption ])
Cons = Cons.T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [ ]:
# Задание 1.10.3

Inc * 0.87

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [ ]:
# Задание 1.10.4
Inc*0.87 - Cons


array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

# End
