# Start

In [2]:
import warnings; warnings.simplefilter('ignore')

import random

import pandas as pd
import numpy as np
import os
import re

import matplotlib.pyplot as plt
import seaborn as sns
import cufflinks as cf
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

project_dir = r'/content/drive/My Drive/Colab Notebooks/'

%matplotlib inline


## 1.2 Векторы


In [3]:
# Задание 1.2.1

apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])
apartment

array([5.950e+01, 3.140e+01, 1.900e+01, 2.000e+00, 6.055e+04, 2.000e+00])

In [4]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]

In [5]:
apartment = np.delete(apartment, [0, 1])

In [6]:
apartment = np.append(apartment, share_living_space)

In [8]:
len(apartment)

5

In [10]:
round(apartment[-1], 2)

0.53

In [11]:
# Задание 1.2.2
len(apartment)


5

In [25]:
# Задание 1.2.3

t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

t[5], t[1]

(28, 14)

In [24]:
t.min() - t[0], t.max() - t[6]

(0, 0)

## 1.3 Базовые операции над векторами

In [29]:
# Задание 1.3.3

alex = np.array([120,150,90])
alex_w = np.array([130,130,130])
alex_g = np.array([2, 3, 2.5])*72

In [30]:
alex_g

array([144., 216., 180.])

In [31]:
alex + alex_w + alex_g

array([394., 496., 400.])

## 1.4. Линейная комбинация

In [33]:
# Задание 1.4.1
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])
k = np.array([2,-3,5])

x * k[0] + y * k[1] + u * k[2]

array([7, 7])

In [37]:
# Задание 1.4.2

make_count = np.array([3, 4, 5, 9])
sell_count = np.array([1, 5, 3, 6])
make_price = 200
sell_price = 400

sell_count * sell_price - make_count * make_price

array([-200, 1200,  200,  600])

In [38]:
# Задание 1.4.3
x = np.array([-1, -2])
y = np.array([1, 2])

x + y

array([0, 0])

In [41]:
x = np.array([-3,-2])
y = np.array([1,1])
u = np.array([4,3])
x + y * (-1) + u

array([0, 0])

In [42]:
x = np.array([-3,-2])
y = np.array([1,1])

x + 2 * y

array([-1,  0])

## 1.5. Скалярное произведение

In [43]:
# Задание 1.5.2

x = np.array([4,5,-1])
y = np.array([2,0,1])
np.dot(x, y)

7

In [45]:
# Задание 1.5.4

x = np.array([4,6,1])

round(np.sqrt(np.dot(x,x)), 2)

7.28

In [ ]:
# Задание 1.5.5
# вектора называются ортогональными, если их скалярное произведение равно нулю


# End
